
version: 2

models:
    - name: dim_dates
      description: "dbt model for dates"
      columns:
          - name: DATEKEY
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: date_filter
      description: "dbt incremental model for dates up till current date"
      columns:
          - name: DATEKEY
            description: "The primary key for this table"