
version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
  

    - name: snowflake_customer_purchase
      description: "Total purchases for customers in snowflake sample data"
      columns:
          - name: c_custkey
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
                
    - name: first_dbt_model


sources:
  - name: sf_sample
    database: snowflake_sample_data
    schema: tpch_sf1
    tables: 
      - name: customer
      - name: orders 