
version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                -relationships:
                  to: ref('my_first_dbt_model')
                  field: id

    - name: snowflake_customer_purchase
      description: "Total purchases for customers in snowflake sample data"
      columns:
          - name: c_custkey
            description: "The primary key for this table"
            tests:
                - unique
                - not_null